# Configurações do pedido-process
# Kafka Bahia Configuration
kafka:
  bootstrapServers: "tcp://cloud-services.demos.mulesoft.com:30858"
  topic: "pedido.new"
  kafkaManagerUrl: "http://cloud-services.demos.mulesoft.com:31018"
  kafkaManagerUsername: "admin"
  kafkaManagerPassword: "mulesoft123"
  
# APIs Configuration (System Layer)
apis:
  pedido:
    host: "pedido-sys-sh06qr.qfq181.bra-s1.cloudhub.io"
    port: "443"
    basePath: "/api"
    protocol: "HTTPS"
  estoque:
    host: "estoque-sys-sh06qr.qfq181.bra-s1.cloudhub.io" 
    port: "443"
    basePath: "/api"
    protocol: "HTTPS"
  fatura:
    host: "fatura-sys-sh06qr.qfq181.bra-s1.cloudhub.io"
    port: "443"
    basePath: "/api"
    protocol: "HTTPS"

# HTTP Listener Configuration
http:
  listener:
    host: "0.0.0.0"
    port: "8081"
    basePath: "/process"